export const POPULAR_PRODUCT_LIST_REQUEST='POPULAR_PRODUCT_LIST_REQUEST';
export const SEARCH_PRODUCT_LIST_REQUEST='SEARCH_PRODUCT_LIST_REQUEST';

export const POPULAR_PRODUCT_LIST_SUCCESS='POPULAR_PRODUCT_LIST_SUCCESS';
export const SEARCH_PRODUCT_LIST_SUCCESS='SEARCH_PRODUCT_LIST_SUCCESS';

export const POPULAR_PRODUCT_LIST_FAILURE   ='POPULAR_PRODUCT_LIST_FAILURE';
export const SEARCH_PRODUCT_PRODUCT_LIST_FAILURE   ='SEARCH_PRODUCT_PRODUCT_LIST_FAILURE';

export const LOCATION_REQUEST='LOCATION_REQUEST';
export const LOCATION_SUCCESS='LOCATION_SUCCESS';
export const LOCATION_FAILURE   ='LOCATION_FAILURE';

export const SEARCH_INPUT   ='SEARCH_INPUT';

export const CART_REQUEST = 'CART_REQUEST';
export const CART_FAILURE = 'CART_FAILURE';
export const CART_SUCCESS = 'CART_SUCCESS';

export const CART_ITEM_ADD_SUCCESS = 'CART_ITEM_ADD_SUCCESS';
export const CART_ITEM_REMOVE_SUCCESS = 'CART_ITEM_REMOVE_SUCCESS';

export const SHOPS_LIST_REQUEST = 'SHOPS_LIST_REQUEST';
export const SHOPS_LIST_SUCCESS = 'SHOPS_LIST_SUCCESS';
export const SHOPS_LIST_FAILURE = 'SHOPS_LIST_FAILURE';

export const SELECT_CATEGORY_SUCCESS = 'SELECT_CATEGORY_SUCCESS';
