export const POPULAR_PRODUCT_LIST_REQUEST='POPULAR_PRODUCT_LIST_REQUEST';
export const DISCOUNTED_PRODUCT_LIST_REQUEST='DISCOUNTED_PRODUCT_LIST_REQUEST';
export const MORE_PRODUCT_LIST_REQUEST='MORE_PRODUCT_LIST_REQUEST';
export const SEARCH_PRODUCT_LIST_REQUEST='SEARCH_PRODUCT_LIST_REQUEST';


export const POPULAR_PRODUCT_LIST_SUCCESS='POPULAR_PRODUCT_LIST_SUCCESS';
export const DISCOUNTED_PRODUCT_LIST_SUCCESS='DISCOUNTED_PRODUCT_LIST_SUCCESS';
export const MORE_PRODUCT_LIST_SUCCESS='MORE_PRODUCT_LIST_SUCCESS';
export const SEARCH_PRODUCT_LIST_SUCCESS='SEARCH_PRODUCT_LIST_SUCCESS';


export const POPULAR_PRODUCT_LIST_FAILURE   ='POPULAR_PRODUCT_LIST_FAILURE';
export const DISCOUNTED_PRODUCT_LIST_FAILURE   ='DISCOUNTED_PRODUCT_LIST_FAILURE';
export const MORE_PRODUCT_LIST_FAILURE   ='MORE_PRODUCT_LIST_FAILURE';
export const SEARCH_PRODUCT_PRODUCT_LIST_FAILURE   ='SEARCH_PRODUCT_PRODUCT_LIST_FAILURE';

export const LOCATION_REQUEST='LOCATION_REQUEST';
export const LOCATION_SUCCESS='LOCATION_SUCCESS';
export const LOCATION_FAILURE   ='LOCATION_FAILURE';

export const SEARCH_INPUT   ='SEARCH_INPUT';
